server:
  port: 30010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        group: xtt-cloud-oa
        file-extension: yaml
        namespace: public
      discovery:
        server-addr: nacos-server:8848
        group: xtt-cloud-oa
        namespace: public
  config:
    import: optional:nacos:gateway.yaml

# JWT Configuration
#jwt:
#  secret: xtt-cloud-oa-jwt-secret-key-2023
#  expiration: 86400000  # 24 hours in milliseconds
#  refresh-expiration: 604800000  # 7 days in milliseconds

# 其余 gateway/jwt/logging 等统一在 config-init/config/gateway.yaml 维护

# 启动时打印配置信息
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter: DEBUG
    org.springframework.cloud.gateway.handler.predicate: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    xtt.cloud.gateway: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.nacos: DEBUG
    com.alibaba.nacos: DEBUG
    com.alibaba.cloud.nacos: DEBUG
