spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: 'myuser'
    password: 'mypassword'
  main:
    allow-bean-definition-overriding: true
mybatis:
  configuration:
    map-underscore-to-camel-case: truegit