server:
  port: 8020

spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: xtt-cloud-oa
      config:
        server-addr: nacos-server:8848
        group: xtt-cloud-oa
        file-extension: yaml
    loadbalancer:
      enabled: true
  config:
    import:
      - optional:nacos:auth.yaml

# Feign 配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
  httpclient:
    enabled: true
    connection-timeout: 5000
    connection-timer-repeat: 3000
  circuitbreaker:
    enabled: true

# JWT Configuration
jwt:
  secret: xtt-cloud-oa-jwt-secret-key-2023
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

# Logging
logging:
  level:
    xtt.cloud.oa.auth: DEBUG
    org.springframework.security: DEBUG
